VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "AssistenteConferenciaFiscal"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'TODO: Criar assistente de conferência fiscal para gerar relatórios de conferência com um clique.
'TODO: Criar assistente de verificação de inconsistências C100/C190.


